name: env_postCKG_test
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - argon2-cffi=20.1.0=py36haf1e3a3_1
  - async_generator=1.10=py36h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py36haf1e3a3_1000
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h2432673_2
  - cffi=1.14.3=py36hed5b41f_0
  - chardet=3.0.4=py36_1003
  - cryptography=3.1.1=py36hddc9c9b_0
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - freetype=2.10.4=ha233b18_0
  - icu=67.1=h4a8c4bd_0
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2019.4=233
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jedi=0.17.2=py36_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py36_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.2.0=py36h04f5b5a_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.1.0=hcb84e12_1
  - libuv=1.38.0=h0b31af3_0
  - lz4-c=1.9.2=h79c402e_3
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py36h181983e_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.2.0=py36hc64f4ea_0
  - mkl_random=1.1.1=py36h959d312_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.4.1=py_0
  - nodejs=14.6.0=hdde0ff8_0
  - notebook=6.1.4=py36_0
  - numpy=1.19.2=py36h456fd55_0
  - numpy-base=1.19.2=py36hcfb5961_0
  - olefile=0.46=py36_0
  - openssl=1.1.1h=haf1e3a3_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py36hb1e8313_0
  - pandoc=2.11=h0dc7051_0
  - pandocfilters=1.4.2=py36_1
  - parso=0.7.0=py_0
  - patsy=0.5.1=py36_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=8.0.1=py36h5270095_0
  - pip=20.2.4=py36_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.17.3=py36haf1e3a3_0
  - pysocks=1.7.1=py36_0
  - python=3.6.12=h26836e1_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=py_0
  - pyzmq=19.0.2=py36hb1e8313_1
  - readline=8.0=h1de35cc_0
  - requests=2.24.0=py_0
  - scipy=1.5.2=py36h912ce22_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=50.3.0=py36h0dc7051_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=hffcf06c_0
  - statsmodels=0.12.0=py36haf1e3a3_0
  - terminado=0.9.1=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.0.4=py36h1de35cc_1
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py36h9f0ad1d_4
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.3=hb1e8313_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
  - pip:
    - clustergrammer2==0.17.0
    - joblib==0.17.0
    - scikit-learn==0.23.2
    - sklearn==0.0
    - threadpoolctl==2.1.0
prefix: /Users/niulili/anaconda3/envs/env_postCKG
