########################
dataDirectory: '../../../data'
#Import directory
import_directory: '../../../data/imports'
#Archive directory
archive_directory: '../../../data/archive'
#Stats directory
stats_directory: '../../../data/imports/stats'
#experiments import directory
experiments_directory: '../../../data/imports/experiments'
#databases import diretory
databases_directory: '../../../data/imports/databases'
#ontologies import diretory
ontologies_directory: '../../../data/imports/ontologies'
#users directory
users_directory: '../../../data/imports/users'

download: True

cypher_queries_file: 'cypher.yml'

statsFile: 'stats.hdf'
statsCols: 
    - 'date'
    - 'time'
    - 'dataset'
    - 'filename'
    - 'file_size'
    - 'Imported_number'
    - 'Import_type'
    - 'name'

#Full Graph
graph: 
    - ontologies
    - chromosomes
    - genes
    - transcripts
    - proteins
    - annotations
    - modified_proteins
    - complexes
    - ppi
    - diseases
    - biomarkers
    - drugs
    - known_variants
    - clinical variants
    - pathology_expression
    - mentions
    - internal
    - functional_regions
    - side effects
    - metabolite
    - food
    - gwas
    - pathway
    - published
    - project
    - experiment
    - user
    - protein_structure

#Imports 
ontology_entities: 
    - 'Disease'
    - 'Tissue'
    - 'Biological_process'
    - 'Molecular_function'
    - 'Cellular_component'
    - 'Modification'
    - 'Clinical_variable'
    - 'Phenotype'
    - 'Experiment'
#Database resources
#Modified proteins
modified_proteins_resources:
    - 'psp'
#Protein complexes
complexes_resources:
    - 'CORUM'
#Protein-protein interactions
curated_PPI_resources:
    - 'IntAct'
compiled_PPI_resources:
    - 'STRING'
PPI_action_resources:
    - 'STRING'
#Disease associations
disease_resources: 
    - ['Protein','DisGEnet']
#Pathology Expression
pathology_expression_resources: 
    - 'HPA'
#Drug associations, indications and actions
curated_drug_resources:
    - 'DGIdb'
    - 'CGI'
    - 'OncoKB'
compiled_drug_resources:
    - 'STITCH'
drug_action_resources:
    - 'STITCH'
side_effects_resources:
    - 'SIDER'

#Variants
clinical_variant_resources:
    - 'CGI'
    - 'OncoKB'

#Pathways
pathway_resources:
    - 'Reactome'
    - 'SMPDB'

#Metabolites
metabolite_resources:
    - 'hmdb'

#Food
food_resources:
    - 'FooDB'

#Internal Databases entities
internalEntities:
    - ['Protein','Disease']
    - ['Protein', 'Tissue']
    - ['Protein','Cellular_component']

#Mentions entities
mentionEntities: 
    - 'Disease'
    - 'Tissue'
    - 'Protein'
    - 'Drug'
publicationEntities:
    - 'GWAS_study'
