data exploration:
    wgcna:
        data:
            proteomics: processed
            rnaseq: processed
            clinical: processed
        analyses:
            - wgcna
        plots:
            - wgcnaplots
        store_analysis: True
        args:
            drop_cols_exp:
                - subject
                - group
                - sample
                - index
            drop_cols_cli:
                - index
                - subject
                - group
                - biological_sample
            RsquaredCut: 0.8
            networkType: 'unsigned'
            minModuleSize: 30
            deepSplit: 2
            pamRespectsDendro: False
            merge_modules: True
            MEDissThres: 0.25
            verbose: 0
    clinical_correlation:
        data: 
            longitudinal_proteomics: processed
            clinical: processed
        analyses:
            - multi_correlation
        plots:
            - network
        store_analysis: True
        args:
            on: 
                - subject
                - group
            source: node1
            target: node2
            title: 'Clinical-Proteomics correlation network'
            format: edgelist
            values: weight
            dist: False
            node_properties: {}
            maxLinkWidth: 6
            maxRadius: 20
            node_size: 'degree'
            cutoff: 0.5
            subject: subject
            cutoff_abs: True
            color_weight: True
            communities_algorithm: louvain
            width: 1600
            height: 1600