args:
    imputation: True
    imputation_method: distribution 
    missing_method: at_least_x_per_group
    missing_max: 5
    value_col: LFQ intensity
    index:
        - group
        - sample
        - subject
overview: #section
    peptides:
        data: number of peptides
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of peptides
            title: 'Number of peptides identified per group'
    proteins:
        data: number of proteins
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of proteins
            title: 'Number of proteins identified per group'
    modifications:
        data: number of modified proteins
        analyses: []
        plots:
            - facetplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            class: type
            x_title: Analytical sample
            y_title: number of modified proteins
            plot_type: bar
            title: 'Number of modified proteins identified per type'
    ranking:
        data: 
            - processed
            - protein biomarkers 
        analyses: 
            - ranking_with_markers
        plots:
            - ranking
            - basicTable
        args:
            drop_columns: 
                - sample
                - subject
            columns:
                - name
                - y
            data: processed
            markers: protein biomarkers
            identifier: identifier
            marker_of: disease
            annotate: True
            group: group
            index: True
            x_title: Ranking of proteins
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: Protein ranking
    coefficient_variation:
        data: processed
        analyses:
            - coefficient_of_variation
        plots:
            - scatterplot_matrix
        args:
            drop_columns:
                - sample
                - subject
            columns:
                - name
                - y
            group: group
            index: True
            x_title: '%CV'
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: 'Proteins %CV'
data exploration:
    # stratification:
    #     description: '# Principal Component Analysis

    #                     **Principal component analysis (PCA)** is a statistical procedure that uses an orthogonal transformation to convert a set of observations 
    #                     of possibly correlated variables (entities each of which takes on various numerical values) into a set of values of linearly uncorrelated 
    #                     variables called principal components. This transformation is defined in such a way that the first principal component has the largest possible variance 
    #                     (that is, accounts for as much of the variability in the data as possible), and each succeeding component in turn has the highest variance possible under 
    #                     the constraint that it is orthogonal to the preceding components. The resulting vectors (each being a linear combination of the variables and containing n observations) 
    #                     are an uncorrelated orthogonal basis set. PCA is sensitive to the relative scaling of the original variables. [Wikipedia](https://en.wikipedia.org/wiki/Principal_component_analysis)'
    #     data: processed
    #     analyses:
    #         - pca
    #         #- tsne
    #         #- umap
    #     plots:
    #         - pca
    #     args:
    #         x_title: PC1
    #         y_title: PC2
    #         components: 2
    #         perplexity: 40
    #         n_iter: 1000
    #         init: 'pca'
    #         width: 1000
    #         height: 700
    #         loadings: 15
    #         title: 'Sample stratification'
    regulation:
        description: '# Regulation
        
                        **Analysis of variance (ANOVA)** is a collection of statistical models and their associated estimation procedures (such as the "variation" among and between groups) 
                        used to analyze the differences among group means in a sample. ANOVA was developed by statistician and evolutionary biologist Ronald Fisher. The ANOVA is based on the law of 
                        total variance, where the observed variance in a particular variable is partitioned into components attributable to different sources of variation. In its simplest form, 
                        ANOVA provides a statistical test of whether two or more population means are equal, and therefore generalizes the t-test beyond two means.[Wikipedia](https://en.wikipedia.org/wiki/Analysis_of_variance)'
        data: processed
        analyses:
            - anova
        plots:
            - basicTable
            - volcanoplot
        store_analysis: True
        args:
            alpha: 0.05
            s0: 1
            fc: 2.0
            group: 'group'
            subject: subject
            colorscale: 'Blues'
            showscale: False
            marker_size: 10
            permutations: 250
            x_title: logFC
            y_title: -log(pvalue)
            drop_cols:
                - sample
                - subject
            name: name
            title: 'Differential regulation ANOVA'
    correlation:
        data: processed
        analyses:
            - correlation
        plots:
            - network
            #- heatmap
        store_analysis: True
        args:
            source: node1
            target: node2
            title: 'Features correlation network'
            format: edgelist
            values: weight
            dist: False
            node_properties: {}
            maxLinkWidth: 6
            maxRadius: 20
            node_size: 'degree'
            cutoff: 0.5
            subject: subject
            cutoff_abs: True
            color_weight: True
            communities_algorithm: louvain
            width: 1600
            height: 1600
data associations:
    interaction_network:
        data: regulated
        analyses: []
        plots:
            - network
        args:
            use:
                columns: identifiers
            source: node1
            target: node2
            title: 'Protein-Protein interaction network'
            format: edgelist
            values: score
            dist: False
            node_properties: {}
            width: 1600
            height: 1600
            maxLinkWidth: 7
            maxRadius: 20
            color_weight: False
            node_size: 'ev_centrality'
            communities_algorithm: louvain
    drug_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of drugs targetting differentially regulated proteins'
    disease_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of diseases associated with the differentially regulated proteins'
    literature_associations:
        data: regulated
        analyses: 
            - publications_abstracts
        plots:
            - basicTable
            - wordcloud
        args:
            use:
                columns: identifiers
            height: 700
            width: 1300
            stopwords: 
                - BACKGROUND
                - CONCLUSION
                - RESULT
                - METHOD
                - CONCLUSIONS
                - RESULTS
                - METHODS
            max_words: 400
            max_font_size: 600
            margin: 1
            text_col: 'abstract'
            title: 'List of publications mentioning regulated proteins together with related diseases'
enrichment:
    go_enrichment:
        data: 
            - regulation table
            - go annotation
        analyses:
            - regulation_enrichment
        plots:
            - basicTable
        store_analysis: False
        args:
            regulation_data: regulation table
            annotation: go annotation
            identifier: identifier
            groups:
                - group1
                - group2
            annotation_type: Biological_processes
            annotation_col: annotation
            reject_col: rejected
            method: fisher
            title: 'Gene Ontology Enrichment'
    pathway_enrichment:
        data: 
            - regulation table
            - pathway annotation
        analyses:
            - regulation_enrichment
        plots:
            - basicTable
        store_analysis: False
        args:
            regulation_data: regulation table
            annotation: pathway annotation
            identifier: identifier
            groups:
                - group1
                - group2
            annotation_type: Pathways
            annotation_col: annotation
            reject_col: rejected
            method: fisher
            title: 'Pathway Enrichment'