args:
    filter_samples: False
    filter_samples_percent: 0.5
    imputation: True
    imputation_method: distribution
    missing_shift: 1.8
    missing_nstd: 0.30
    missing_method: percentage
    missing_per_group: True
    missing_max: 0.3
    value_col: LFQ_intensity
    extra_identifier: name
    normalize: False
    normalization_method: 'median'
    normalize_group: False
    normalize_by: 'samples'
    index:
        - group
        - sample
        - subject
overview: #section
    overview statistics:
        data: processed
        analyses:
            - summary
        plots:
            - multiTable
        store_analysis: True
        args:
            title: Summary Statistics
    peptides:
        data: number of peptides
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of peptides
            title: 'Number of peptides identified per group'
    proteins:
        data: number of proteins
        analyses: []
        plots:
            - barplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            width: 900
            height: 700
            x_title: Analytical sample
            y_title: number of proteins
            title: 'Number of proteins identified per group'
    modifications:
        data: number of modified proteins
        analyses: []
        plots:
            - facetplot
            - basicTable
        args:
            x: x
            y: y
            group: group
            class: type
            x_title: Analytical sample
            y_title: number of modified proteins
            plot_type: bar
            title: 'Number of modified proteins identified per type'
    coefficient_variation:
        data: processed
        analyses:
            - coefficient_of_variation
        plots:
            - scatterplot_matrix
        args:
            drop_columns:
                - sample
                - subject
            columns:
                - name
                - y
            group: group
            index: True
            x_title: '%CV'
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: 'Proteins %CV'
    quality_control:
        data:
            - processed
            - tissue qcmarkers
        analyses:
            - qcmarkers
        plots:
            - qcmarkers_boxplot
        args:
            sample_col: sample
            group_col : group
            identifier_col: identifier
            qcidentifier_col: identifier
            qcclass_col: class
            x: sample
            y: z-score
            color: group
            facet: class
            height: 900
            width: 2500
            title: 'Quality Control markers'
    ranking:
        data:
            - processed
            - protein biomarkers
        analyses:
            - ranking_with_markers
        plots:
            - ranking
            - basicTable
        args:
            drop_columns:
                - sample
                - subject
            columns:
                - name
                - y
            data: processed
            markers: protein biomarkers
            identifier: identifier
            marker_of: disease
            annotate: True
            group: group
            index: True
            x_title: Ranking of proteins
            y_title: log2 LFQ intensity
            size: 9
            height: 900
            width: 1500
            title: Protein ranking
data exploration:
    stratification_pca:
        description: '# Principal Component Analysis

                         **Principal component analysis (PCA)** is a statistical procedure that uses an orthogonal transformation to convert a set of observations
                         of possibly correlated variables (entities each of which takes on various numerical values) into a set of values of linearly uncorrelated
                         variables called principal components. This transformation is defined in such a way that the first principal component has the largest possible variance
                         (that is, accounts for as much of the variability in the data as possible), and each succeeding component in turn has the highest variance possible under
                         the constraint that it is orthogonal to the preceding components. The resulting vectors (each being a linear combination of the variables and containing n observations)
                         are an uncorrelated orthogonal basis set. PCA is sensitive to the relative scaling of the original variables. [Wikipedia](https://en.wikipedia.org/wiki/Principal_component_analysis)'
        data: processed
        analyses:
            - pca
        plots:
            - pca
        args:
            hovering_cols:
                - sample
            drop_cols:
                - sample
                - subject
            group: group
            x_title: PC1
            y_title: PC2
            components: 2
            init: 'pca'
            width: 1000
            height: 700
            loadings: 15
            factor: 20
            title: 'Sample stratification with PCA'
    functional stratification:
        description: '# Functional PCA (Single-Sample GSEA)'
        data:
            - processed
            - protein go annotation
        analyses:
            - functional_pca
        plots:
            - pca
        args:
            hovering_cols:
                - sample
            data_id: processed
            annotation_id: protein go annotation
            annotation_col: annotation
            identifier_col: identifier
            index:
                - group
                - sample
                - subject
            key: nes
            group: group
            min_size: 15
            x_title: PC1
            y_title: PC2
            components: 2
            factor: 1
            width: 1000
            height: 700
            loadings: 15
            title: 'Sample Functional Stratification'
    regulation:
        description: '# Regulation

                        **Mixed Analysis of variance (ANOVA)**'
        data: 
            - processed
            - metadata
        analyses:
            - mixed_anova
        plots:
            - basicTable
        store_analysis: True
        args:
            alpha: 0.05
            fc: 2.0
            within: 'group'
            between: 'group2'
            subject: subject
            colorscale: 'Blues'
            showscale: False
            marker_size: 10
            permutations: 0
            num_annotations: 50
            x_title: log2FC
            y_title: -log10(pvalue)
            drop_cols:
                - sample
            name: name
            title: 'Differential regulation Mixed ANOVA within Subject and between Condition'
    correlation:
        data: processed
        analyses:
            - repeated_measurements_correlation
        plots:
            - network
        store_analysis: True
        args:
            source: node1
            target: node2
            title: 'Protein-Protein correlation network'
            format: edgelist
            values: weight
            dist: False
            node_properties: {}
            maxLinkWidth: 6
            maxRadius: 20
            node_size: 'degree'
            cutoff: 0.5
            subject: subject
            cutoff_abs: True
            color_weight: True
            communities_algorithm: affinity_propagation
            width: 1600
            height: 1600
data associations:
    protein_interaction_network:
        data: regulated
        analyses: []
        plots:
            - network
        store_analysis: True
        args:
            use:
                columns: identifiers
            source: node1
            target: node2
            title: 'Protein-Protein interaction network'
            format: edgelist
            values: score
            dist: False
            node_properties: {}
            width: 1600
            height: 1600
            maxLinkWidth: 7
            maxRadius: 20
            color_weight: False
            node_size: 'degree'
            communities_algorithm: louvain
    protein_complex_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        store_analysis: True
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of complexes regulated proteins belong to'
    protein_drug_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        store_analysis: True
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of drugs targetting differentially regulated proteins'
    protein_disease_associations:
        data: regulated
        analyses: []
        plots:
            - basicTable
        store_analysis: True
        args:
            use:
                columns: identifiers
            height: 700
            width: 900
            title: 'List of diseases associated with the differentially regulated proteins'
    literature_associations:
        data: regulated
        analyses:
            - publications_abstracts
        plots:
            - basicTable
            - wordcloud
        store_analysis: True
        args:
            use:
                columns: identifiers
            height: 700
            width: 1300
            stopwords:
                - BACKGROUND
                - CONCLUSION
                - RESULT
                - METHOD
                - CONCLUSIONS
                - RESULTS
                - METHODS
            max_words: 400
            max_font_size: 600
            margin: 1
            text_col: 'abstract'
            title: 'List of publications mentioning regulated proteins together with related diseases'
enrichment:
    protein_go_enrichment:
        data:
            - regulation table
            - protein go annotation
        analyses:
            - up_down_enrichment
        plots:
            - basicTable
            - enrichment_plot
        store_analysis: True
        args:
            regulation_data: regulation table
            annotation: protein go annotation
            identifier: identifier
            groups:
                - group1
                - group2
            annotation_type: Biological_processes
            annotation_col: annotation
            reject_col: rejected
            method: fisher
            lfc_cutoff: 1
            alpha: 0.05
            width: 1300
            title: 'Gene Ontology Enrichment'
    protein_pathway_enrichment:
        data:
            - regulation table
            - protein pathway annotation
        analyses:
            - up_down_enrichment
        plots:
            - basicTable
            - enrichment_plot
        store_analysis: True
        args:
            regulation_data: regulation table
            annotation: protein pathway annotation
            identifier: identifier
            groups:
                - group1
                - group2
            annotation_type: Pathways
            annotation_col: annotation
            reject_col: rejected
            lfc_cutoff: 1
            alpha: 0.05
            width: 1300
            method: fisher
            title: 'Pathway Enrichment'