#Databases
databases : 
    - "DrugBank"
    - "Jensenlab"
    - "HGNC"
    - "RefSeq"
    - "UniProt"
    - "DisGEnet"
    - "STITCH"
    - "STRING"
    - "IntAct"
    - "MutationDs"
    - "Mentions"
    - "HMDB"
    - "PathwayCommons"
    - "GWASCatalog"
    - "DGIdb" 
    - "CancerGenomeInterpreter"
    - "OncoKB"
    - "SIDER"
    - "PhosphoSitePlus"
    - "SIGNOR"
    - "CORUM"
    - "FooDB"
    - "Exposome Explorer"
    - "HPA"
    - "Reactome"
    - "SMPDB"
    - "Pfam"

sources : 
    "Drug": "DrugBank"
    "Metabolite": "HMDB"
    "Protein": "UniProt"
    "Gene": "HGNC"
    "Food": "FooDB"
    "Pathway": "Reactome"
    "Disease": "DO"
